# Generated by Django 5.0 on 2023-12-11 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newad", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ad",
            old_name="ad_name",
            new_name="name",
        ),
        migrations.CreateModel(
            name="DailyVisitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("count", models.PositiveIntegerField(default=0)),
                (
                    "ad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="newad.ad"
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="newad.location"
                    ),
                ),
            ],
        ),
    ]
